version: '3.7'

services:
  sample:
    container_name: dharmadict-generate
    build:
      context: .
      dockerfile: Dockerfile-generate
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
