version: '3.7'

services:

  sample:
    container_name: dharmadict-start
    build:
      context: .
      dockerfile: Dockerfile-start
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true