# Generated by Django 3.0.8 on 2021-04-10 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('modificator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
