# Generated by Django 3.0.8 on 2021-04-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pagesmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagesModel',
            new_name='Page',
        ),
    ]
