# Generated by Django 3.0.8 on 2021-04-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210410_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
