# Generated by Django 3.0.8 on 2021-04-10 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210410_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='modificator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
