# Generated by Django 3.0.8 on 2021-04-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210410_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.TextField(max_length=200),
        ),
    ]
