# Generated by Django 3.0.8 on 2021-04-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210411_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='topmenu',
            field=models.BooleanField(default=False),
        ),
    ]
