# Generated by Django 3.0.8 on 2021-04-18 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_page_topmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wylie', models.CharField(max_length=216)),
                ('sanscrit', models.CharField(max_length=216)),
                ('tibetian', models.CharField(max_length=216)),
                ('sa2ru', models.CharField(max_length=216)),
                ('sa2en', models.CharField(max_length=216)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=216)),
                ('interpretation', models.TextField(blank=True, default='', null=True)),
                ('context', models.TextField(blank=True, default='', null=True)),
                ('rationale', models.TextField(blank=True, default='', null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='core.Language')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='core.Term')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transtator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
