# Generated by Django 3.0.8 on 2021-04-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210418_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='tibetian',
        ),
        migrations.AddField(
            model_name='term',
            name='tibetan',
            field=models.CharField(blank=True, default='', max_length=216),
        ),
        migrations.AlterField(
            model_name='term',
            name='sa2en',
            field=models.CharField(blank=True, default='', max_length=216),
        ),
        migrations.AlterField(
            model_name='term',
            name='sa2ru',
            field=models.CharField(blank=True, default='', max_length=216),
        ),
        migrations.AlterField(
            model_name='term',
            name='sanscrit',
            field=models.CharField(blank=True, default='', max_length=216),
        ),
    ]
