# Generated by Django 3.0.8 on 2021-04-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210420_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isTranslator',
            field=models.BooleanField(default=False),
        ),
    ]
