# Generated by Django 3.0.8 on 2021-04-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_istranslator'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='mainMenuLink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='mainPageLink',
            field=models.BooleanField(default=False),
        ),
    ]
