# Generated by Django 3.0.8 on 2021-04-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210425_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='topmenu',
        ),
    ]
