# Generated by Django 3.0.8 on 2021-05-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_page_topmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='wylie',
            field=models.CharField(max_length=216, unique=True),
        ),
    ]
