# Generated by Django 3.0.8 on 2021-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210501_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='shortTitle',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
