# Generated by Django 3.0.8 on 2021-05-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210502_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
