# Generated by Django 3.0.8 on 2021-05-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210502_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_page', to='core.Page'),
        ),
    ]
