# Generated by Django 3.0.8 on 2021-05-04 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_customuser_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='core.Term'),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to=settings.AUTH_USER_MODEL),
        ),
    ]
