# Generated by Django 3.0.8 on 2021-05-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210504_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.Page'),
        ),
    ]
