# Generated by Django 3.0.8 on 2021-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210529_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(blank=True, default='static/img/user.jpg', null=True, upload_to='static/img'),
        ),
    ]
